version: '3'
services:
  #PHP Service
  bookstore_app:
    build:
      context: .
      dockerfile: app.docker
    container_name: bookstore_app
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bookstore_network
    links:
      - bookstore_mysql:db

  #Nginx Service
  bookstore_web:
    image: nginx:1.21.1
    container_name: bookstore_web
    ports:
      - 8081:80
    volumes:
      - ../:/var/www
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bookstore_network
    depends_on:
      - bookstore_app

  # MySQL Service
  bookstore_mysql:
    image: mysql:8
    container_name: bookstore_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33062:3306
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - bookstore_network
    volumes:
      - bookstore-mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

#Docker Networks
networks:
  bookstore_network:
    driver: bridge
volumes:
  bookstore-mysql: {}
